.TH RDECAY "1" "February 2017" "rdecay 1.1.2" "User Commands"
.SH NAME
rdecay \- simuliert den radioaktiven Zerfall
.SH SYNOPSIS
.B rdecay
[\fI\,OPTION\/\fR]...
.SH BESCHREIBUNG
Simuliert den radioaktiven Zerfall.
.SH OPTIONEN
.TP
\fB\-\-fps\fR ZAHL
setzt die Frames pro Sekunde auf ZAHL
.TP
\fB\-\-showfps\fR
schreibt die FPS auf die Standardausgab
.TP
\fB\-h\fR, \fB\-\-help\fR
diese Hilfe anzeigen und beenden
.TP
\fB\-v\fR, \fB\-\-version\fR
Versionsinformation anzeigen und beenden
.SH AUTOR
Geschrieben von Johannes Weißl.
.SH FEHLERBERICHTE
Fehlerberichte bitte an jargon@molb.org.
.SH COPYRIGHT
Copyright \(co 2004\-2017 Johannes Weißl
.br
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt keine Garantie; auch nicht für VERKAUFBARKEIT oder FÜR SPEZIELLE ZWECKE.
