.TH RDECAY "1" "March 2004" "rdecay 1.01" "User Commands"
.SH NAME
rdecay \- simuliert den radioaktiven Zerfall
.SH SYNOPSIS
.B rdecay
[\fIOPTION\fR]...
.SH BESCHREIBUNG
Simuliert den radioaktiven Zerfall.
.SH OPTIONEN
.TP
\fB\-\-fps\fR ZAHL
setzt die Frames pro Sekunde auf ZAHL
.TP
\fB\-\-showfps\fR
schreibt die FPS auf die Standardausgab
.TP
\fB\-h\fR, \fB\-\-help\fR
diese Hilfe anzeigen und beenden
.TP
\fB\-v\fR, \fB\-\-version\fR
Versionsinformation anzeigen und beenden
.SH AUTOR
Geschrieben von Johannes Weißl.
.SH FEHLERBERICHTE
Fehlerberichte bitte an johannes.weissl@gmx.de.
.SH COPYRIGHT
Copyright \(co 2004 Johannes Weißl
.br
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt keine Garantie; auch nicht für VERKAUFBARKEIT oder FÜR SPEZIELLE ZWECKE.
