.TH RDECAY "1" "February 2017" "rdecay 1.1.2" "User Commands"
.SH NAME
rdecay \- simulates the radioactive decay
.SH SYNOPSIS
.B rdecay
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
Simulates the radioactive decay.
.SH OPTIONS
.TP
\fB\-\-fps\fR NUMBER
set frames per second to NUMBER
.TP
\fB\-\-showfps\fR
print fps to stdout
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
output version information and exit
.SH AUTHOR
Written by Johannes Weiﬂl.
.SH "REPORTING BUGS"
Report bugs to jargon@molb.org.
.SH COPYRIGHT
Copyright \(co 2004\-2017 Johannes Weiﬂl
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
