name: Test
on:
  push:
  schedule:
    - cron: '0 0 1 * *'  # monthly
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install autopoint libgtk2.0-dev
      - uses: actions/checkout@v3
      - run: ./bootstrap.sh && ./configure && make
  macos:
    runs-on: macos-latest
    steps:
      - run: brew install automake gtk+ gsl
      - uses: actions/checkout@v3
      - run: ./bootstrap.sh && ./configure && make
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: autotools gettext-devel gcc
      - uses: actions/checkout@v3
      - run: ./bootstrap.sh && ./configure && make
